#!/bin/ash

# Hosts 自动合并脚本

echo "开始更新合并 hosts 文件..."

# 删除之前的 AWAvenue-Ads-Rule 条目
echo "删除之前的 AWAvenue-Ads-Rule 条目..."
sed -i '/# AWAvenue-Ads-Rule Start/,/# AWAvenue-Ads-Rule End/d' /etc/hosts

# 拉取 AWAvenue-Ads-Rule 的 hosts 文件，并添加起始和结束标记
# 删除 AWAvenue-Ads-Rule 其中的 "127.0.0.1 localhost" 和 "::1 localhost" 条目，因为原始 hosts 文件已自带
#echo "下拉取并合并 AWAvenue-Ads-Rule 的 hosts 文件..."
#curl https://cdn.jsdelivr.net/gh/TG-Twilight/AWAvenue-Ads-Rule@main/Filters/AWAvenue-Ads-Rule-hosts.txt | \
#    sed '/127.0.0.1 localhost/d; /::1 localhost/d; 1s/^/# AWAvenue-Ads-Rule Start\n/; $s/$/\n# AWAvenue-Ads-Rule End/' >> /etc/hosts

# 删除空行
#echo "删除空行..."
#sed -i '/^$/d' /etc/hosts

# 删除之前的GitHub520 Host 和 Fetch Github(hosts) 条目
echo "删除之前的 GitHub520 Host 和 Fetch Github(hosts) 条目..."
sed -i '/# GitHub520 Host Start/,/# GitHub520 Host End/d' /etc/hosts
sed -i '/# fetch-github-hosts begin/,/# fetch-github-hosts end/d' /etc/hosts

# 拉取 GitHub520 Host 和 Fetch Github 的 hosts 文件
echo "拉取并合并 GitHub520 Host 和 Fetch Github 的 hosts 文件..."
curl https://hosts.gitcdn.top/hosts.txt >> /etc/hosts
curl https://cdn.jsdelivr.net/gh/521xueweihan/GitHub520@main/hosts >> /etc/hosts 

# 删除空行
echo "删除空行..."
sed -i '/^$/d' /etc/hosts

# 删除多余注释信息
echo "删除多余注释信息..."
sed -i '/!/d' /etc/hosts

echo "hosts 文件更新合并完成！"

# 将 hosts 文件编码转换为 UTF-8
#echo "将 hosts 文件编码转换为 UTF-8..."
#iconv -f ANSI -t UTF-8 /etc/hosts > /tmp/hosts.tmp && mv /tmp/hosts.tmp /etc/hosts

#echo "hosts 文件编码已转换为 UTF-8！"

# 检查是否存在 OpenClash 的启动脚本
if [ -f "/etc/init.d/openclash" ]; then
    # 如果存在 OpenClash 的启动脚本，则重启 OpenClash
    echo "检测到 OpenClash 存在，正在重启 OpenClash..."
    /etc/init.d/openclash restart
    echo "已重启 OpenClash 和 Dnsmasq，Hosts 已生效！"
else
    # 如果不存在 OpenClash 的启动脚本，则直接重启 dnsmasq
    echo "未检测到 OpenClash，正在直接重启 Dnsmasq..."
    /etc/init.d/dnsmasq restart
    echo "已重启 Dnsmasq，Hosts 已生效！"
fi

